"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AppHeader } from "@/components/app-header";
import { AppSidebar } from "@/components/app-sidebar";
import { admitTeleSession, endTeleSession, getDoctorTeleSessions, type TeleSession } from "@/lib/demo-telehealth-store";
import { MOCK_USERS } from "@/lib/mock-users";

export default function DoctorTeleconsultationPage() {
  const doctor = MOCK_USERS.find((user) => user.role === "medico")!;
  const doctorId = "MED-001";
  const [sessions, setSessions] = useState<TeleSession[]>([]);
  const [notice, setNotice] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => setSessions(getDoctorTeleSessions(doctorId)), 0); return () => window.clearTimeout(timer); }, []);
  function refresh() { setSessions(getDoctorTeleSessions(doctorId)); }
  function admit(id: string) { const result = admitTeleSession(id, doctorId); setNotice(result ? `${result.patientName} fue admitida a la sala.` : "No fue posible admitir a la paciente. Actualiza la sala e inténtalo nuevamente."); refresh(); }
  function finish(id: string) { const result = endTeleSession(id, doctorId); setNotice(result ? "Teleconsulta finalizada. La cita se actualizó y el acceso fue invalidado." : "La sesión no se puede finalizar desde el estado actual."); refresh(); }
  return <div className="min-h-screen bg-background md:flex"><AppSidebar role="medico" active="tele" /><main className="min-w-0 flex-1 pb-22 md:pb-0"><AppHeader role="medico" name={doctor.name} /><div className="mx-auto max-w-5xl p-5 sm:p-8"><Link href="/medico" className="text-sm font-semibold text-primary hover:underline">← Inicio</Link><header className="mt-5"><p className="text-sm font-semibold tracking-wide text-secondary">SALA VIRTUAL</p><h1 className="mt-1 text-3xl font-bold text-text-primary">Teleconsultas</h1><p className="mt-2 text-text-secondary">Solo aparecen pacientes asignados a tu sala virtual. Admite a la persona autorizada y revisa su contexto antes de atender.</p></header>{notice && <p role="status" className="mt-5 rounded-xl bg-info-container p-4 text-sm text-info">{notice}</p>}<section className="mt-7 rounded-2xl border border-divider bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-text-primary">Pacientes conectados</h2><p className="mt-1 text-sm text-text-secondary">Actualiza la sala para verificar nuevas conexiones.</p></div><button onClick={refresh} className="rounded-lg border border-divider px-4 py-2.5 text-sm font-semibold text-text-secondary hover:bg-surface-secondary">Actualizar sala</button></div><div className="mt-5 divide-y divide-divider">{sessions.length ? sessions.map((session) => <article key={session.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="font-semibold text-text-primary">{session.patientName}</p><p className="mt-1 text-sm text-text-secondary">{session.specialty} · cita {session.appointmentId}</p><p className="mt-1 text-xs text-text-tertiary">{session.audit.at(-1)}</p></div><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${session.status === "WAITING" ? "bg-warning-container text-warning" : "bg-success-container text-success"}`}>{session.status === "WAITING" ? "En espera" : "En consulta"}</span><Link href="/medico/agenda/AGEN-004" className="text-sm font-semibold text-primary hover:underline">Ver contexto</Link>{session.status === "WAITING" ? <button onClick={() => admit(session.id)} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-on-primary hover:bg-primary-hover">Admitir</button> : <button onClick={() => finish(session.id)} className="rounded-lg border border-error px-4 py-2.5 text-sm font-semibold text-error hover:bg-error-container">Finalizar</button>}</div></article>) : <div className="rounded-xl bg-surface-secondary p-8 text-center"><p className="font-semibold text-text-primary">No hay pacientes en tu sala</p><p className="mt-2 text-sm text-text-secondary">Las sesiones terminadas o asignadas a otros médicos no aparecen aquí.</p></div>}</div></section></div></main></div>;
}
