"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

import { apiJson } from "@/lib/api/client";

type Referral = { id: string; patient_id: string; patient_name: string; patient_carnet: string; specialty_name: string; priority: "ROUTINE" | "PRIORITY" | "URGENT"; reason: string; comment_for_specialist: string; status: "PENDING_ASSIGNMENT" | "ASSIGNED" | "IN_PROGRESS" | "CLOSED" | "RETURNED"; requested_at: string; requested_by_name: string; assigned_staff_name: string | null; appointment_id: string | null; scheduled_for: string | null };

const priority = { ROUTINE: "Rutinaria", PRIORITY: "Prioritaria", URGENT: "Urgente" };
const status = { PENDING_ASSIGNMENT: "Por programar", ASSIGNED: "Programada", IN_PROGRESS: "En atención", CLOSED: "Cerrada", RETURNED: "Devuelta" };

export function AdministrativeReferralInbox() {
  const [items, setItems] = useState<Referral[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [tab, setTab] = useState<"pending" | "history">("pending");
  useEffect(() => { void apiJson<Referral[]>("/api/administrative/referrals").then(setItems).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "No se pudieron cargar las derivaciones.")).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => items.filter((item) => tab === "pending" ? item.status === "PENDING_ASSIGNMENT" : item.status !== "PENDING_ASSIGNMENT"), [items, tab]);
  const pending = items.filter((item) => item.status === "PENDING_ASSIGNMENT").length;
  return <><header><p className="text-sm font-semibold tracking-wide text-primary">DERIVACIONES CLÍNICAS</p><h1 className="mt-1 text-3xl font-bold text-text-primary">Bandeja de derivaciones</h1><p className="mt-2 max-w-3xl text-text-secondary">Revisa el criterio del médico solicitante y programa al estudiante con un especialista y cupo compatible.</p></header>
    <div className="mt-7 flex gap-2 border-b border-divider pb-4"><button onClick={() => setTab("pending")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "pending" ? "bg-primary text-on-primary" : "bg-surface-secondary text-text-secondary"}`}>Por programar ({pending})</button><button onClick={() => setTab("history")} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab === "history" ? "bg-primary text-on-primary" : "bg-surface-secondary text-text-secondary"}`}>Historial</button></div>
    {loading ? <p className="py-16 text-center text-sm text-text-secondary">Cargando derivaciones…</p> : error ? <p className="mt-6 rounded-xl bg-error-container p-4 text-sm text-error">{error}</p> : <div className="mt-6 grid gap-4">{visible.map((item) => <article key={item.id} className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-wide text-primary">{item.specialty_name.toUpperCase()}</p><h2 className="mt-1 text-xl font-bold text-text-primary">{item.patient_name}</h2><p className="mt-1 text-sm text-text-secondary">Carnet {item.patient_carnet} · Solicitada por {item.requested_by_name}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${item.priority === "URGENT" ? "bg-error-container text-error" : item.priority === "PRIORITY" ? "bg-warning-container text-warning" : "bg-primary-container text-primary"}`}>{priority[item.priority]} · {status[item.status]}</span></div><div className="mt-5 grid gap-4 border-t border-divider pt-4 md:grid-cols-2"><div><p className="text-xs font-semibold text-text-secondary">MOTIVO CLÍNICO</p><p className="mt-1 text-sm leading-6 text-text-primary">{item.reason}</p></div><div><p className="text-xs font-semibold text-text-secondary">RESUMEN PARA ESPECIALISTA</p><p className="mt-1 text-sm leading-6 text-text-primary">{item.comment_for_specialist}</p></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-text-secondary">{item.assigned_staff_name ? `Especialista: ${item.assigned_staff_name}` : "Aún sin especialista asignado"}{item.scheduled_for ? ` · ${new Date(item.scheduled_for).toLocaleString("es-BO", { dateStyle: "medium", timeStyle: "short" })}` : ""}</p>{item.status === "PENDING_ASSIGNMENT" && <Link href={`/administrativo/check-in?patientId=${item.patient_id}&referralId=${item.id}`} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-on-primary">Asignar especialista y horario</Link>}</div></article>)}{!visible.length && <p className="rounded-2xl border border-dashed border-divider bg-surface p-10 text-center text-sm text-text-secondary">{tab === "pending" ? "No hay derivaciones pendientes de programación." : "Aún no hay historial de derivaciones."}</p>}</div>}</>;
}
