"use client";

import { useMemo, useState } from "react";
import { appointmentStatusClass, appointmentStatusLabel, boliviaDate, formatAppointmentTime, useMedicalAppointments } from "@/components/medical-appointments";

export function MedicalAgenda() {
  const { appointments, loading, error } = useMedicalAppointments(); const [selectedDate, setSelectedDate] = useState(() => boliviaDate(new Date())); const agenda = useMemo(() => appointments.filter((item) => boliviaDate(item.scheduledFor) === selectedDate), [appointments, selectedDate]); const dates = useMemo(() => [...new Set(appointments.map((item) => boliviaDate(item.scheduledFor)))].sort(), [appointments]);
  return <section className="mt-7 rounded-2xl border border-divider bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-lg font-bold text-text-primary">Citas asignadas</h2><p className="mt-1 text-sm text-text-secondary">Sólo se muestran citas que pertenecen a tu ficha de personal.</p></div><label className="text-sm font-semibold text-text-primary">Fecha<input type="date" value={selectedDate} onChange={(event) => setSelectedDate(event.target.value)} className="mt-2 block rounded-lg border border-divider bg-surface px-3 py-2 text-sm font-normal outline-none focus:border-primary" /></label></div>{dates.length > 1 && <div className="mt-5 flex flex-wrap gap-2">{dates.slice(0, 10).map((date) => <button key={date} onClick={() => setSelectedDate(date)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${selectedDate === date ? "bg-primary text-on-primary" : "bg-surface-secondary text-text-secondary hover:bg-primary-container"}`}>{date}</button>)}</div>}{error ? <p className="mt-6 rounded-lg bg-error-container p-4 text-sm text-error">{error}</p> : loading ? <p className="py-12 text-center text-sm text-text-secondary">Cargando agenda…</p> : agenda.length ? <div className="mt-6 divide-y divide-divider">{agenda.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 py-5 first:pt-0"><div><p className="font-bold text-text-primary">{item.patient?.fullName ?? "Paciente asignado"}</p><p className="mt-1 text-sm text-text-secondary">{formatAppointmentTime(item.scheduledFor)}{item.endsAt ? ` – ${new Intl.DateTimeFormat("es-BO", { timeZone: "America/La_Paz", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(item.endsAt))}` : ""}</p><p className="mt-1 text-sm text-text-secondary">{item.specialty} · {item.patient ? `CI ${item.patient.carnet}` : "Datos restringidos"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${appointmentStatusClass(item.status)}`}>{appointmentStatusLabel(item.status)}</span></article>)}</div> : <div className="mt-6 rounded-xl bg-surface-secondary p-8 text-center text-sm text-text-secondary">No tienes citas asignadas para esta fecha.</div>}</section>;
}
