"use client";

import { useRef, useState } from "react";

const documentTypes = [
  ["BLOOD_CHEMISTRY", "Química sanguínea"], ["LAB_RESULT", "Resultado de laboratorio"], ["RADIOGRAPH", "Radiografía / imagen"],
  ["PRESCRIPTION", "Receta médica"], ["CLINICAL_PHOTO", "Fotografía clínica"], ["REFERRAL_DOCUMENT", "Documento de derivación"], ["OTHER", "Otro archivo"],
] as const;

export function MedicalDocumentUploader({ patientId, encounterId, fixedType, compact = false, onUploaded }: { patientId: string; encounterId: string; fixedType?: string; compact?: boolean; onUploaded?: (documentType: string) => void }) {
  const input = useRef<HTMLInputElement>(null); const [documentType, setDocumentType] = useState(fixedType ?? "OTHER"); const [description, setDescription] = useState(""); const [studyDate, setStudyDate] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function upload() {
    const file = input.current?.files?.[0]; if (!file) { setMessage("Selecciona un archivo primero."); return; }
    setLoading(true); setMessage(""); const form = new FormData(); form.set("file", file); form.set("patientId", patientId); form.set("encounterId", encounterId); form.set("documentType", fixedType ?? documentType); form.set("description", description); form.set("studyDate", studyDate);
    try { const response = await fetch("/api/medical/documents", { method: "POST", body: form }); const payload = await response.json().catch(() => ({ ok: false, error: "Respuesta inválida." })); if (!response.ok || !payload.ok) throw new Error(payload.error ?? "No se pudo cargar el archivo."); if (input.current) input.current.value = ""; setDescription(""); setStudyDate(""); setMessage("Archivo almacenado de forma segura."); onUploaded?.(fixedType ?? documentType); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "No se pudo cargar el archivo."); } finally { setLoading(false); }
  }
  return <section className={`rounded-xl border border-divider bg-surface-secondary ${compact ? "p-4" : "p-5"}`}><div><h3 className="font-bold text-text-primary">{fixedType === "BLOOD_CHEMISTRY" ? "Adjuntar química sanguínea" : "Adjuntar archivo clínico"}</h3><p className="mt-1 text-xs leading-5 text-text-secondary">PDF, JPG, PNG o WEBP · máximo 15 MiB · se guarda en el bucket clínico privado.</p></div><div className="mt-4 grid gap-3">{!fixedType && <label><span className="text-xs font-semibold text-text-primary">Tipo</span><select value={documentType} onChange={(event) => setDocumentType(event.target.value)} className="mt-1 block w-full rounded-lg border border-divider bg-surface px-3 py-2 text-sm outline-none focus:border-primary">{documentTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<input ref={input} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className="block w-full text-sm text-text-secondary file:mr-3 file:rounded-lg file:border-0 file:bg-primary-container file:px-3 file:py-2 file:text-sm file:font-semibold file:text-primary hover:file:bg-primary-100" /><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descripción opcional" className="w-full rounded-lg border border-divider bg-surface px-3 py-2 text-sm outline-none focus:border-primary" /><label className="text-xs font-semibold text-text-primary">Fecha del estudio (opcional)<input type="date" value={studyDate} onChange={(event) => setStudyDate(event.target.value)} className="mt-1 block w-full rounded-lg border border-divider bg-surface px-3 py-2 text-sm font-normal outline-none focus:border-primary" /></label><button type="button" onClick={upload} disabled={loading} className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-on-primary hover:bg-primary-hover disabled:opacity-50">{loading ? "Subiendo…" : "Subir archivo"}</button>{message && <p role="status" className="text-xs text-text-secondary">{message}</p>}</div></section>;
}
