"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { appointmentStatusClass, appointmentStatusLabel, formatAppointmentTime, useMedicalAppointments } from "@/components/medical-appointments";

function age(birthDate: string | null) { if (!birthDate) return "—"; const today = new Date(); const birthday = new Date(`${birthDate}T00:00:00`); let result = today.getFullYear() - birthday.getFullYear(); if (today.getMonth() < birthday.getMonth() || (today.getMonth() === birthday.getMonth() && today.getDate() < birthday.getDate())) result -= 1; return `${result} años`; }

export function MedicalPatientList() {
  const { appointments, loading, error } = useMedicalAppointments(); const [query, setQuery] = useState("");
  const patients = useMemo(() => { const grouped = new Map<string, typeof appointments>(); appointments.forEach((appointment) => { if (appointment.patient) grouped.set(appointment.patient.id, [...(grouped.get(appointment.patient.id) ?? []), appointment]); }); return [...grouped.values()].map((items) => ({ patient: items[0].patient!, appointments: items })).sort((a, b) => a.patient.fullName.localeCompare(b.patient.fullName)); }, [appointments]);
  const shown = patients.filter(({ patient }) => `${patient.fullName} ${patient.carnet} ${patient.registrationCode}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><label className="block max-w-md"><span className="sr-only">Buscar paciente</span><input value={query} onChange={(event) => setQuery(event.target.value)} type="search" placeholder="Buscar por nombre, CI o registro" className="w-full rounded-lg border border-divider bg-surface px-4 py-2.5 text-sm text-text-primary outline-none focus:border-primary focus:ring-2 focus:ring-primary-200" /></label>{error ? <p className="mt-5 rounded-lg bg-error-container p-4 text-sm text-error">{error}</p> : loading ? <p className="py-12 text-center text-sm text-text-secondary">Cargando pacientes autorizados…</p> : shown.length ? <div className="mt-6 divide-y divide-divider">{shown.map(({ patient, appointments: related }) => { const next = related.filter((item) => item.status === "SCHEDULED" || item.status === "CHECKED_IN")[0] ?? related[0]; return <article key={patient.id} className="flex flex-wrap items-center justify-between gap-4 py-5 first:pt-0"><div><Link href={`/medico/pacientes/${patient.id}`} className="font-bold text-text-primary hover:text-primary hover:underline">{patient.fullName}</Link><p className="mt-1 text-sm text-text-secondary">CI {patient.carnet} · Reg. {patient.registrationCode} · {age(patient.birthDate)}</p><p className="mt-2 text-sm text-text-secondary">{related.length} cita{related.length === 1 ? "" : "s"} vinculada{related.length === 1 ? "" : "s"} a tu cuenta.</p><Link href={`/medico/pacientes/${patient.id}`} className="mt-3 inline-block text-sm font-semibold text-primary hover:underline">Abrir ficha clínica →</Link></div><div className="min-w-52 text-left sm:text-right"><p className="text-sm font-semibold text-text-primary">{formatAppointmentTime(next.scheduledFor)}</p><p className="mt-1 text-xs text-text-secondary">{next.specialty}</p><span className={`mt-2 inline-block rounded-full px-3 py-1 text-xs font-semibold ${appointmentStatusClass(next.status)}`}>{appointmentStatusLabel(next.status)}</span></div></article>; })}</div> : <div className="mt-6 rounded-xl bg-surface-secondary p-7 text-center text-sm text-text-secondary">{query ? "No hay coincidencias en tus pacientes." : "Todavía no tienes pacientes vinculados. Administración debe asignar una solicitud a un cupo publicado por tu cuenta."}</div>}</section>;
}
