type DailyActivity = {
  activity_day: string;
  encounter_type: "INITIAL" | "SPECIALTY";
  specialty_name: string | null;
  total_closed: number;
};

type ComplianceRow = {
  patient_id: string;
  carnet: string;
  full_name: string;
  career_name: string;
  first_closed_encounter_at: string | null;
  compliance_status: "COMPLIANT" | "PENDING";
};

export function OperationalReports({ activities, scope }: { activities: DailyActivity[]; scope: "administrative" | "medical" }) {
  const total = activities.reduce((sum, activity) => sum + Number(activity.total_closed), 0);

  return <div className="space-y-6"><header className="border-b border-divider pb-5"><p className="text-sm font-semibold tracking-wide text-primary">REPORTES CLÍNICOS</p><h1 className="mt-1 text-3xl font-bold text-text-primary">Actividad clínica diaria</h1><p className="mt-2 text-text-secondary">{scope === "administrative" ? "Resumen institucional de atenciones cerradas." : "Resumen de las atenciones cerradas bajo tu responsabilidad."}</p></header><section className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-divider bg-surface p-5"><p className="text-sm font-semibold text-text-secondary">Atenciones cerradas</p><p className="mt-2 text-3xl font-black text-text-primary">{total}</p></article><article className="rounded-2xl border border-divider bg-surface p-5"><p className="text-sm font-semibold text-text-secondary">Grupos con actividad</p><p className="mt-2 text-3xl font-black text-text-primary">{activities.length}</p></article></section><section className="overflow-hidden rounded-2xl border border-divider bg-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-divider bg-surface-secondary text-text-secondary"><tr><th className="px-5 py-4 font-semibold">Fecha</th><th className="px-5 py-4 font-semibold">Tipo de atención</th><th className="px-5 py-4 font-semibold">Especialidad</th><th className="px-5 py-4 text-right font-semibold">Cerradas</th></tr></thead><tbody className="divide-y divide-divider">{activities.map((activity, index) => <tr key={`${activity.activity_day}-${activity.encounter_type}-${activity.specialty_name ?? index}`}><td className="px-5 py-4">{new Date(`${activity.activity_day}T12:00:00`).toLocaleDateString("es-BO")}</td><td className="px-5 py-4">{activity.encounter_type === "INITIAL" ? "Revisión" : "Especialidad"}</td><td className="px-5 py-4">{activity.specialty_name ?? "—"}</td><td className="px-5 py-4 text-right font-bold">{activity.total_closed}</td></tr>)}{!activities.length && <tr><td colSpan={4} className="px-5 py-12 text-center text-text-secondary">No hay atenciones cerradas en el período actual.</td></tr>}</tbody></table></div></section><p className="text-xs leading-5 text-text-tertiary">Los reportes nominales, filtros avanzados y exportaciones volverán cuando exista la RPC auditable de reporte; no se muestran datos de demostración.</p></div>;
}

export function ComplianceReport({ rows }: { rows: ComplianceRow[] }) {
  const completed = rows.filter((row) => row.compliance_status === "COMPLIANT").length;
  return <div className="space-y-6"><header className="border-b border-divider pb-5"><p className="text-sm font-semibold tracking-wide text-primary">CUMPLIMIENTO</p><h1 className="mt-1 text-3xl font-bold text-text-primary">Control de revisión médica</h1><p className="mt-2 text-text-secondary">El cumplimiento se calcula desde atenciones clínicas cerradas y matrículas registradas.</p></header><section className="grid gap-4 sm:grid-cols-3"><article className="rounded-2xl border border-divider bg-surface p-5"><p className="text-sm font-semibold text-text-secondary">Estudiantes</p><p className="mt-2 text-3xl font-black text-text-primary">{rows.length}</p></article><article className="rounded-2xl border border-divider bg-surface p-5"><p className="text-sm font-semibold text-text-secondary">Cumplieron</p><p className="mt-2 text-3xl font-black text-success">{completed}</p></article><article className="rounded-2xl border border-divider bg-surface p-5"><p className="text-sm font-semibold text-text-secondary">Pendientes</p><p className="mt-2 text-3xl font-black text-warning">{rows.length - completed}</p></article></section><section className="overflow-hidden rounded-2xl border border-divider bg-surface"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-divider bg-surface-secondary text-text-secondary"><tr><th className="px-5 py-4 font-semibold">Estudiante</th><th className="px-5 py-4 font-semibold">Carrera</th><th className="px-5 py-4 font-semibold">Primera atención cerrada</th><th className="px-5 py-4 font-semibold">Estado</th></tr></thead><tbody className="divide-y divide-divider">{rows.map((row) => <tr key={row.patient_id}><td className="px-5 py-4"><p className="font-semibold text-text-primary">{row.full_name}</p><p className="text-xs text-text-secondary">{row.carnet}</p></td><td className="px-5 py-4">{row.career_name}</td><td className="px-5 py-4">{row.first_closed_encounter_at ? new Date(row.first_closed_encounter_at).toLocaleDateString("es-BO") : "—"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.compliance_status === "COMPLIANT" ? "bg-success-container text-success" : "bg-warning-container text-warning"}`}>{row.compliance_status === "COMPLIANT" ? "Cumplido" : "Pendiente"}</span></td></tr>)}{!rows.length && <tr><td colSpan={4} className="px-5 py-12 text-center text-text-secondary">No hay matrículas disponibles para calcular cumplimiento.</td></tr>}</tbody></table></div></section></div>;
}
