"use client";

export type SpecialtyHistoryDraft = {
  schemaVersion: 1;
  specialtyCode: string;
  personalHistory: { pathological: string; surgical: string; allergic: string; family: string };
  ophthalmology: { currentIllness: string; visualAcuityRight: string; visualAcuityLeft: string };
  gynecology: {
    onset: "" | "ACUTE" | "SUBACUTE" | "CHRONIC";
    symptoms: string; previousTreatments: string; menarcheAge: string; menstrualPattern: "" | "REGULAR" | "IRREGULAR";
    cycleDays: string; lastMenstrualPeriod: string; dysmenorrhea: "" | "YES" | "NO"; leucorrhea: "" | "YES" | "NO";
    previousSti: "" | "YES" | "NO"; stiDetails: string; contraceptiveMethods: string[]; contraceptiveOther: string;
    lastPap: string; papResult: "" | "NORMAL" | "ALTERED"; papDetails: string;
    familyGynecologicalCancer: boolean; familyBreastCancer: boolean; familyDiabetes: boolean; familyOther: string;
    breastExam: string; externalGenitalExam: string; speculumExam: string; vaginalExam: string; cervixExam: string;
  };
};

export function emptySpecialtyHistory(specialtyCode: string): SpecialtyHistoryDraft {
  return { schemaVersion: 1, specialtyCode, personalHistory: { pathological: "", surgical: "", allergic: "", family: "" }, ophthalmology: { currentIllness: "", visualAcuityRight: "", visualAcuityLeft: "" }, gynecology: { onset: "", symptoms: "", previousTreatments: "", menarcheAge: "", menstrualPattern: "", cycleDays: "", lastMenstrualPeriod: "", dysmenorrhea: "", leucorrhea: "", previousSti: "", stiDetails: "", contraceptiveMethods: [], contraceptiveOther: "", lastPap: "", papResult: "", papDetails: "", familyGynecologicalCancer: false, familyBreastCancer: false, familyDiabetes: false, familyOther: "", breastExam: "", externalGenitalExam: "", speculumExam: "", vaginalExam: "", cervixExam: "" } };
}

const input = "mt-2 w-full rounded-lg border border-divider bg-surface px-3 py-2.5 text-sm outline-none focus:border-primary";
const area = `${input} resize-y`;
const yesNo = [["", "No registrado"], ["YES", "Sí"], ["NO", "No"]] as const;

export function SpecialtyHistoryForm({ value, onChange }: { value: SpecialtyHistoryDraft; onChange: (next: SpecialtyHistoryDraft) => void }) {
  const eye = (key: keyof SpecialtyHistoryDraft["ophthalmology"], next: string) => onChange({ ...value, ophthalmology: { ...value.ophthalmology, [key]: next } });
  const gyn = <K extends keyof SpecialtyHistoryDraft["gynecology"]>(key: K, next: SpecialtyHistoryDraft["gynecology"][K]) => onChange({ ...value, gynecology: { ...value.gynecology, [key]: next } });
  const isEye = value.specialtyCode === "OPHTHALMOLOGY";
  const isGyn = value.specialtyCode === "GYNECOLOGY";
  const title = isEye ? "HISTORIA OFTALMOLÓGICA" : isGyn ? "HISTORIA GINECOLÓGICA" : "ANTECEDENTES DE ESPECIALIDAD";
  return <div className="space-y-6">
    <section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><p className="text-sm font-semibold tracking-wide text-primary">{title}</p><p className="mt-1 text-sm text-text-secondary">Los antecedentes generales se cargan desde el perfil clínico compartido. Aquí se registran únicamente los datos propios de esta especialidad.</p></section>
    {isEye && <section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><p className="text-sm font-semibold tracking-wide text-primary">EXAMEN OFTALMOLÓGICO</p><label className="mt-5 block"><span className="text-sm font-semibold text-text-primary">Enfermedad actual</span><textarea value={value.ophthalmology.currentIllness} onChange={(e) => eye("currentIllness", e.target.value)} rows={4} className={area} /></label><div className="mt-5 grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-semibold text-text-primary">Agudeza visual · ojo derecho (V.D.)</span><input value={value.ophthalmology.visualAcuityRight} onChange={(e) => eye("visualAcuityRight",e.target.value)} className={input} /></label><label><span className="text-sm font-semibold text-text-primary">Agudeza visual · ojo izquierdo (V.I.)</span><input value={value.ophthalmology.visualAcuityLeft} onChange={(e) => eye("visualAcuityLeft",e.target.value)} className={input} /></label></div></section>}
    {isGyn && <GynecologyFields value={value.gynecology} change={gyn} />}
  </div>;
}

function GynecologyFields({ value, change }: { value: SpecialtyHistoryDraft["gynecology"]; change: <K extends keyof SpecialtyHistoryDraft["gynecology"]>(key: K, next: SpecialtyHistoryDraft["gynecology"][K]) => void }) {
  const toggleMethod = (method: string) => change("contraceptiveMethods", value.contraceptiveMethods.includes(method) ? value.contraceptiveMethods.filter((item) => item !== method) : [...value.contraceptiveMethods.filter((item) => item !== "NONE"), method]);
  return <><section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><p className="text-sm font-semibold tracking-wide text-primary">ENFERMEDAD Y ANTECEDENTES GINECOLÓGICOS</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Choice label="Inicio" value={value.onset} onChange={(v) => change("onset",v as SpecialtyHistoryDraft["gynecology"]["onset"])} options={[["","No registrado"],["ACUTE","Agudo"],["SUBACUTE","Subagudo"],["CHRONIC","Crónico"]]} /><label><span className="text-sm font-semibold text-text-primary">Menarca (años)</span><input type="number" min="0" value={value.menarcheAge} onChange={(e) => change("menarcheAge",e.target.value)} className={input} /></label><Choice label="Ritmo menstrual" value={value.menstrualPattern} onChange={(v) => change("menstrualPattern",v as SpecialtyHistoryDraft["gynecology"]["menstrualPattern"])} options={[["","No registrado"],["REGULAR","Regular"],["IRREGULAR","Irregular"]]} /><label><span className="text-sm font-semibold text-text-primary">Ciclo (días)</span><input type="number" min="0" value={value.cycleDays} onChange={(e) => change("cycleDays",e.target.value)} className={input} /></label><label><span className="text-sm font-semibold text-text-primary">FUM</span><input type="date" value={value.lastMenstrualPeriod} onChange={(e) => change("lastMenstrualPeriod",e.target.value)} className={input} /></label><Choice label="Dismenorrea" value={value.dysmenorrhea} onChange={(v) => change("dysmenorrhea",v as SpecialtyHistoryDraft["gynecology"]["dysmenorrhea"])} options={yesNo} /><Choice label="Leucorrea" value={value.leucorrhea} onChange={(v) => change("leucorrhea",v as SpecialtyHistoryDraft["gynecology"]["leucorrhea"])} options={yesNo} /><Choice label="ITS previas" value={value.previousSti} onChange={(v) => change("previousSti",v as SpecialtyHistoryDraft["gynecology"]["previousSti"])} options={yesNo} /></div><label className="mt-5 block"><span className="text-sm font-semibold text-text-primary">Síntomas principales</span><textarea value={value.symptoms} onChange={(e) => change("symptoms",e.target.value)} rows={4} className={area} /></label><label className="mt-5 block"><span className="text-sm font-semibold text-text-primary">Tratamientos previos / detalle de ITS</span><textarea value={`${value.previousTreatments}${value.stiDetails ? `\nITS: ${value.stiDetails}` : ""}`} onChange={(e) => change("previousTreatments",e.target.value)} rows={3} className={area} /></label></section>
  <section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><p className="text-sm font-semibold tracking-wide text-primary">ANTICONCEPCIÓN, PAP Y FAMILIARES</p><div className="mt-5 flex flex-wrap gap-3">{[["NONE","Ninguno"],["ORAL","Oral"],["INJECTABLE","Inyectable"],["IUD","DIU"],["IMPLANT","Implante"],["CONDOM","Preservativo"]].map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.contraceptiveMethods.includes(key)} onChange={() => key === "NONE" ? change("contraceptiveMethods", value.contraceptiveMethods.includes(key) ? [] : [key]) : toggleMethod(key)} />{label}</label>)}</div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-semibold text-text-primary">Otro método</span><input value={value.contraceptiveOther} onChange={(e) => change("contraceptiveOther",e.target.value)} className={input} /></label><label><span className="text-sm font-semibold text-text-primary">Último PAP</span><input type="date" value={value.lastPap} onChange={(e) => change("lastPap",e.target.value)} className={input} /></label><Choice label="Resultado PAP" value={value.papResult} onChange={(v) => change("papResult",v as SpecialtyHistoryDraft["gynecology"]["papResult"])} options={[["","No registrado"],["NORMAL","Normal"],["ALTERED","Alterado"]]} /><label><span className="text-sm font-semibold text-text-primary">Detalle PAP / otros familiares</span><input value={value.papDetails} onChange={(e) => change("papDetails",e.target.value)} className={input} /></label></div><div className="mt-5 flex flex-wrap gap-3 text-sm">{[["familyGynecologicalCancer","CA ginecológico"],["familyBreastCancer","CA mama"],["familyDiabetes","Diabetes"]].map(([key,label]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={value[key as keyof typeof value] as boolean} onChange={(e) => change(key as "familyGynecologicalCancer" | "familyBreastCancer" | "familyDiabetes", e.target.checked)} />{label}</label>)}</div></section>
  <section className="rounded-2xl border border-divider bg-surface p-5 sm:p-6"><p className="text-sm font-semibold tracking-wide text-primary">EXAMEN FÍSICO GINECOLÓGICO</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{([['breastExam','Mamas'],['externalGenitalExam','Genitales externos'],['speculumExam','Especuloscopía'],['vaginalExam','Tacto vaginal'],['cervixExam','Cuello uterino']] as const).map(([key,label]) => <label key={key}><span className="text-sm font-semibold text-text-primary">{label}</span><textarea value={value[key]} onChange={(e) => change(key,e.target.value)} rows={3} className={area} /></label>)}</div></section></>;
}

function Choice({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) { return <label><span className="text-sm font-semibold text-text-primary">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className={input}>{options.map(([id,text]) => <option key={id} value={id}>{text}</option>)}</select></label>; }
